### ISSUE TITLE
#US11 Como usuario quiero poder acceder fácilmente a la gestión comercial desde la sección 'Mi perfil' para administrar mis productos o servicios.

### ISSUE THREAD

**Issue by anibal-morales** [Dev-Full-Solutions/AnalizArApp#10]

**Comment by danielpozzo** [comment]
La gestión comercial de los productos y/o servicios de AnalizAr se seguirán gestionando desde la SPA del proyecto. El acceso a dicha funcionalidad quedará en carpeta para la próxima versión del producto AnalizArApp.
