### ISSUE TITLE
#US43 Como usuario quiero ver la funcionalidad completa de la activity "Mi Cuenta" para acceder a los datos comerciales.

### ISSUE THREAD

**Issue by danielpozzo** [Dev-Full-Solutions/AnalizArApp#101]
- [x] Modificar el título a mayúsculas para uniformar el estilo del mismo respecto a las especificaciones del manual de estilos de la aplicación.
- [x] Modificar el tono de color de los campos según las especificaciones del manual de estilos de la aplicación.
- [x] Incorporar el atributo "Alt" en imágenes de la activity para cumplir con los requisitos de accesibilidad para personas dificultades de visión.
- [x] Añadir la opción para salir de la aplicación mediante ícono.

**Comment by anibal-morales** [comment]
Logre resolver el problema que tenia con los margenes. Me faltaria el icono para cerrar sesion.
Queda pendiente saber si se tiene que completar el atributo ContentDescription en cada campo para ofrecer accesibilidad.
