### ISSUE TITLE
#US44 Como usuario quiero ver la funcionalidad completa de la activity "Mis Alarmas 1" para activar las alertas de consumo de manera individual.

### ISSUE THREAD

**Issue by danielpozzo** [Dev-Full-Solutions/AnalizArApp#102]
- [x] Modificar el título a mayúsculas para uniformar el estilo del mismo respecto a las especificaciones del manual de estilos de la aplicación.
- [x] Añadir funcionalidad a los botones  de tipo "Switch" y el cambio de color al activarse.
- [x] Incorporar al botón "+" la funcionalidad para añadir alertas.
- [x] Agregar la accesibilidad al Titulo, en base al manual institucional del proyecto.
- [x] Agregar la accesibilidad al botón “+”,en base al manual institucional del proyecto.
- [x] Agregar la accesibilidad a los textos, en base al manual institucional del proyecto.
- [x] Dar funcionalidad de Activado/Desactivado al botón Switch.
- [x] Eliminar las tarjetas estáticas.
- [x] Generar tarjetas dinámicas para que se vallan agregando las alarmas.
- [x] Dar funcionalidad al botón “+”, que al presionarlo lleve a la pantalla para configurar cada alarma.
- [x] Agregar un Scroll para que cuando se vallan agregando las alarmas se puedan ir viendo todas.
- [x] Colocar el botón “+” fijo, debajo de las tarjetas dinámicas, para que cuando se vallan agregando el botón siempre queda debajo.

**Comment by KaterinnePeralta** [comment]
Criterios de Aceptación para la #US44.

- [x] Se han agregados los estilos de texto y los colores correspondientes para poder brindar la accesibilidad requerida.
- [x] Se han identificado las tarjetas dinámicas en la actividad “Mis Alarmas 1”.
- [x] Se han eliminado las tarjetas dinámicas de la interfaz de la actividad.
- [x] Se hicieron pruebas en la actividad “Mis Alarmas 1”, para corroborar que su funcionalidad sea la correcta y que cada elemento funcione bien por separado.
- [x] Se ha notificado a los miembros del equipo acerca de los cambios realizados en la actividad “Mis Alarmas 1”.
- [x] Se ha subido el código de la rama personal local a la rama correspondiente en el repositorio remoto.
- [x] El código se ha fusionado correctamente en la rama develop del repositorio remoto.
- [x] Se ha verificado que los cambios en el repositorio remoto sean reflejo de las tareas completadas en esta US44.
