### ISSUE TITLE
#US47 Como usuario quiero ver la funcionalidad completa de la activity "Main" para poder ingresar a la aplicación mediante logueo o tener la posibilidad de iniciar el tour y que todas esas opciones me sean accesibles.

### ISSUE THREAD

**Issue by danielpozzo** [Dev-Full-Solutions/AnalizArApp#105]
**Objetivos a realizar**

Modificar la funcionalidad del botón "Ingresar" para que redirija a "Login".
Añadir un botón "Tour" para que el usuario pueda iniciar el recorrido por las activities "Onboarding1".
 Incorporar  atributos "Alt" a la pantalla main de la aplicación para cumplir con los requisitos de accesibilidad para personas con dificultades de visión.

**Modificar el botón "Ingresar":**

- [x] Crear un enlace desde el botón "Ingresar" a la actividad "Login".
- [x] Asegurarse de que la transición entre actividades funcione correctamente.
- [x] Realizar pruebas de navegación para verificar que el usuario sea redirigido adecuadamente.

**Agregar el botón "Tour":**

- [x] Diseñar y agregar el botón "Tour" en la interfaz de la actividad "Main".
- [x] Crear un enlace desde el botón "Tour" hacia la actividad Onboarding1, (la cual se conecta con Onboarding2 y luego con Onboarding3 generando asi  el Tour mencionado).
- [x] Asegurarse de que el botón "Tour" sea visible y accesible.
- [x] Realizar pruebas de navegación para verificar que el usuario sea redirigido adecuadamente.

**Incorporar el atributo "Alt" en el logo:**

- [x] Modificar la etiqueta de la imagen del logo de la aplicación para incluir un atributo "Alt".
- [x] El atributo "Alt" debe ser descriptivo y adecuado para usuarios con dificultades de visión.
- [x] Realizar las pruebas correspondientes para verificar que el atributo "Alt" se ajuste a los requisitos.

**Incorporar el atributo "Alt" en el botón INGRESAR:**

- [x] Modificar la etiqueta del botón INGRESAR de la aplicación para incluir un atributo "Alt".
- [x] El atributo "Alt" debe ser descriptivo y adecuado para usuarios con dificultades de visión.
- [x] Realizar las pruebas correspondientes para verificar que el atributo "Alt" se ajuste a los requisitos.

**Incorporar el atributo "Alt" en el botón INICIAR TOUR:**

- [x] Modificar la etiqueta del botón INICIAR TOUR de la aplicación para incluir un atributo "Alt".
- [x] El atributo "Alt" debe ser descriptivo y adecuado para usuarios con dificultades de visión.
- [x] Realizar las pruebas correspondientes para verificar que el atributo "Alt" se ajuste a los requisitos.

**Incorporar el atributo "Alt" en el título:**

- [x] Modificar la etiqueta del título de la aplicación para incluir un atributo "Alt".
- [x] El atributo "Alt" debe ser descriptivo y adecuado para usuarios con dificultades de visión.
- [x] Realizar las pruebas correspondientes para verificar que el atributo "Alt" se ajuste a los requisitos.

**Comment by NoeCoast** [comment]
@NoeCoast

**Comment by NoeCoast** [comment]
Estoy realizando las pruebas de emulación con un dispositivo Moto C con Android 7, un Motorola motor(7) Android 10 y un TLC 6165A con Android 12.

**Comment by NoeCoast** [comment]
Criterios de Aceptación para la User Story #US47 


- [x] El botón "Ingresar" se ha modificado para redirigir correctamente a la actividad "Login".

- [x] La transición entre actividades funciona sin errores.

- [x] Se han realizado pruebas de navegación para verificar que el usuario sea redirigido adecuadamente al presionar el botón "Ingresar".

- [x] Se ha diseñado y agregado el botón "Iniciar Tour" en la interfaz de la actividad "Main".

- [x] El botón "Iniciar Tour" se ha enlazado correctamente con la actividad "Onboarding1", que a su vez se conecta con las actividades "Onboarding2" y "Onboarding3" para crear un recorrido completo.

- [x] El botón "Tour" es visible y accesible para el usuario.

- [x] Se han realizado pruebas de navegación para verificar que el usuario sea redirigido adecuadamente al presionar el botón "Tour".

- [x] La etiqueta de la imagen del logo de la aplicación se ha modificado para incluir un atributo "Alt".

- [x] El atributo "Alt" es descriptivo y adecuado para usuarios con dificultades de visión.

- [x] La etiqueta del botón "Ingresar" de la aplicación se ha modificado para incluir un atributo "Alt".

- [x] El atributo "Alt" es descriptivo y adecuado para usuarios con dificultades de visión.

- [x] Incorporar el atributo "Alt" en el botón "Iniciar Tour":

- [x] La etiqueta del botón "Iniciar Tour" de la aplicación se ha modificado para incluir un atributo "Alt".

- [x] El atributo "Alt" es descriptivo y adecuado para usuarios con dificultades de visión.

- [x] La etiqueta del título de la aplicación se ha modificado para incluir un atributo "Alt".

- [x] El atributo "Alt" es descriptivo y adecuado para usuarios con dificultades de visión.

- [x] Se han realizado pruebas para verificar que los atributos "Alt" cumplen con los requisitos de accesibilidad.

- [x] Se ha subido el código de la rama personal local al repositorio remoto.

- [x] Se ha verificado que los cambios en el repositorio remoto sean reflejo de las tareas completadas en esta User Story.

**Comment by NoeCoast** [comment]
Se da por finalizada la #US47 y procedo a cerrar la misma y a ubicarla en done en el tablero kanban.
