### ISSUE TITLE
#US48 Como usuario quiero ver la funcionalidad completa de la activity "Onboarding 1" para poder realizar el tour de la aplicación y que esta experiencia me resulte accesible.

### ISSUE THREAD

**Issue by danielpozzo** [Dev-Full-Solutions/AnalizArApp#106]
Objetivos a cumplir:

Incorporar el atributo "Alt" en la  activity para cumplir con los requisitos de accesibilidad para personas dificultades de visión.
Eliminar el botón "Atrás".

Incorporar el atributo "Alt" en la imagen de la activity:

- [x] Identificar la imagen o imágenes en la actividad "Onboarding 1" que requieren el atributo "Alt".
- [x] Agregar atributos "Alt" descriptivos y adecuados a estas imágenes para mejorar la accesibilidad.
- [x] Realizar pruebas de accesibilidad para garantizar que los atributos "Alt" se ajusten a los requisitos.

Incorporar el atributo "Alt" en el título del texto de la activity:

- [x] Identificar el título en la actividad "Onboarding 1" que requiera el atributo "Alt".
- [x] Agregar atributos "Alt" descriptivos y adecuados al título para mejorar la accesibilidad.
- [x] Realizar pruebas de accesibilidad para garantizar que los atributos "Alt" se ajusten a los requisitos.

Incorporar el atributo "Alt" en el párrafo del texto de la activity:

- [x] Identificar el párrafo en la actividad "Onboarding 1" que requiera el atributo "Alt".
- [x] Agregar atributos "Alt" descriptivos y adecuados al párrafo para mejorar la accesibilidad.
- [x] Realizar pruebas de accesibilidad para garantizar que los atributos "Alt" se ajusten a los requisitos.

Incorporar el atributo "Alt" en el botón de la activity:

- [x] Identificar el botón en la actividad "Onboarding 1" que requiera el atributo "Alt".
- [x] Agregar atributos "Alt" descriptivos y adecuados al botón para mejorar la accesibilidad.
- [x] Realizar pruebas de accesibilidad para garantizar que los atributos "Alt" se ajusten a los requisitos.

Eliminar el botón "Atrás":

- [x] Identificar la ubicación del botón "Atrás" en la actividad "Onboarding 1".
- [x] Eliminar el botón "Atrás" de la interfaz de la actividad.

- [x] Realizar pruebas en la actividad "Onboarding 1" para asegurarse de que todos los elementos de la actividad funcionen correctamente y que los cambios realizados no afecten negativamente la experiencia del usuario.

- [x] Comunicar los cambios realizados a los miembros del equipo.

**Comment by NoeCoast** [comment]
@NoeCoast

**Comment by NoeCoast** [comment]
Estoy realizando las pruebas de emulación con un dispositivo Moto C con Android 7, un Motorola motor(7) Android 10 y un TLC 6165A con Android 12.

**Comment by NoeCoast** [comment]
**Criterios de Aceptación para la User Story #US48 - Experiencia Accesible en la Activity "Onboarding 1"**



 - [x] Se ha identificado la imagen o imágenes en la actividad "Onboarding 1" que requieren el atributo "Alt".

 - [x] Se han agregado atributos "Alt" descriptivos y adecuados a estas imágenes para mejorar la accesibilidad.

 - [x] Se ha identificado el título en la actividad "Onboarding 1" que requiere el atributo "Alt".

 - [x] Se han agregado atributos "Alt" descriptivos y adecuados al título para mejorar la accesibilidad.

 - [x] Se ha identificado el párrafo en la actividad "Onboarding 1" que requiere el atributo "Alt".

 - [x] Se han agregado atributos "Alt" descriptivos y adecuados al párrafo para mejorar la accesibilidad.

 - [x] Se ha identificado el botón en la actividad "Onboarding 1" que requiere el atributo "Alt".

 - [x] Se han agregado atributos "Alt" descriptivos y adecuados al botón para mejorar la accesibilidad.


 - [x] Se ha identificado la ubicación del botón "Atrás" en la actividad "Onboarding 1".

 - [x] Se ha eliminado el botón "Atrás" de la interfaz de la actividad.

 - [x] Se han realizado pruebas en la actividad "Onboarding 1" para asegurarse de que todos los elementos de la actividad funcionen correctamente y que los cambios realizados no afecten negativamente la experiencia del usuario.


 - [x] Los elementos de la actividad funcionan correctamente después de la implementación de los cambios.


 - [x] Se ha notificado a los miembros del equipo acerca de los cambios realizados en la actividad "Onboarding 1".


 - [x] Se ha subido el código de la rama personal local a la rama correspondiente en el repositorio remoto.

 - [x] El código se ha fusionado correctamente en la rama develop del repositorio remoto.

 - [x] Se ha verificado que los cambios en el repositorio remoto sean reflejo de las tareas completadas en esta User Story.

**Comment by NoeCoast** [comment]
Se da por finalizada la #US48 y procedo a cerrar la misma y a ubicarla en done en el tablero kanban.
