### ISSUE TITLE
#US49 Como usuario quiero ver la funcionalidad completa de la activity "Onboarding 2" para poder continuar con el tour, volver atrás o saltar el tour.

### ISSUE THREAD

**Issue by danielpozzo** [Dev-Full-Solutions/AnalizArApp#107]
- [x] Modificar el título a mayúsculas para uniformar el estilo del mismo respecto a las especificaciones del manual de estilos de la aplicación.
- [x] Incorporar el atributo "Alt" en graficos y/o imágenes de la activity para cumplir con los requisitos de accesibilidad para personas dificultades de visión.
- [x] Incorporar el atributo "Alt" en la imágen de la activity para cumplir con los requisitos de accesibilidad para personas dificultades de visión.
- [x] Añadir la opción "Saltar" para salir del tour de la aplicación y dirigirse al "Login".

**Comment by todotirreno** [comment]
Me la asigno provisoriamente. Si Lau hace andar su IDE me desasigno.

**Comment by todotirreno** [comment]
Definición de terminado: funcional y con mejoras de accesibilidad
