### ISSUE TITLE
#US50 Como usuario quiero ver la funcionalidad completa de la activity "Onboarding 3" para poder completar el tour de la aplicación y loguearme.

### ISSUE THREAD

**Issue by danielpozzo** [Dev-Full-Solutions/AnalizArApp#108]
- [x] Modificar el título a mayúsculas para uniformar el estilo del mismo respecto a las especificaciones del manual de estilos de la aplicación.
- [x] Mejorar los textos eliminando palabra repetidas y que mantenga relación en cuanto al formato de sus predecesoras.
- [x] Incorporar el atributo "Alt" en graficos y/o imágenes de la activity para cumplir con los requisitos de accesibilidad para personas dificultades de visión.

**Comment by todotirreno** [comment]
Definición de terminado: funcional y con adaptación de accesibilidad
