### ISSUE TITLE
#US07 Como usuario quiero recibir notificaciones cuando haya cambios relevantes en los datos personales.

### ISSUE THREAD

**Issue by LauraRodriguez22** [Dev-Full-Solutions/AnalizArApp#12]

**Comment by danielpozzo** [comment]
@anibal-morales esta funcionalidad es continuación del desarrollo de la activity "Mi Cuenta" que desarrollaste en el Sprint 1. Habría que generar las tareas necesarias para abordar su desarrollo y complementarlo al desarrollo anterior.
