### ISSUE TITLE
#TK La aplicación no construye

### ISSUE THREAD

**Issue by todotirreno** [Dev-Full-Solutions/AnalizArApp#128]
En la rama Develop, la aplicación no puede construir. Surgen errores en login.java

**Comment by todotirreno** [comment]
Marco completada.

**Comment by NoeCoast** [comment]
Para tener en cuenta si se desea notificar un bug:



Un error en el código generalmente se registra como una tarea específica (TK) en el sistema de gestión de proyectos. 

Proporcionar una descripción clara y concisa del bug incluyendo información sobre lo que se esperaba que sucediera y lo que realmente ocurrió. Cuanto más detallada sea la descripción, mejor.

Enumerar los pasos necesarios para reproducir el bug. Esto ayuda a identificar y solucionar el problema, lo cual es el objetivo de la notificación.

Si es posible, adjuntar capturas de pantalla que muestren el problema o bien, el código relevante que está relacionado con el error para facilitar la comprensión del problema.

Etiquetar el problema de manera apropiada, como "bug", y asignale una prioridad si es relevante. Esto los organiza y prioriza.

Seguir el progreso del problema a medida que los desarrolladores trabajan en el. Se puede agregar comentarios adicionales de relevancia para su resolución.

Cuando el bug se haya solucionado y verificado, los desarrolladores cerrarán el Issue.
