### ISSUE TITLE
#US13 Como usuario quiero ver mi historial de consumo para poder llevar un control general del mismo 

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizArApp#13]

**Comment by NoeCoast** [comment]
Diseñar la pantalla o la sección de la aplicación que mostrará el historial de consumo eléctrico de manera clara y fácil de entender y de acuerdo a la coherencia de marca del producto.

Crear la funcionalidad que permita a los usuarios acceder a su historial de consumo eléctrico recuperando la información almacenada en la base de datos.

Agregar una opción para que los usuarios puedan filtrar su historial de consumo eléctrico por diferentes períodos de tiempo, como días, semanas, meses, etc.

Asegurarse de que solo los usuarios autenticados puedan acceder a su historial de consumo eléctrico para proteger la privacidad de los datos.

Crear gráficos o visualizaciones que muestren el historial de consumo eléctrico de manera fácil de entender, como gráficos de barras, líneas entre otras opciones.


Realizar pruebas para asegurarse de que la función de historial de consumo eléctrico se integre correctamente con la aplicación y funcione correctamente.


Asegurarse de que la carga y visualización del historial de consumo eléctrico sea rápida y eficiente.

**Comment by NoeCoast** [comment]
Agregué las tareas a la #US13

**Comment by NoeCoast** [comment]
**Criterios de aceptación:**

La pantalla que muestra el historial de consumo eléctrico tiene un diseño claro y coherente con los estándares de diseño de la aplicación y la marca del producto.

La información se presenta de manera fácil de entender, con atención a la usabilidad y legibilidad.

Se han creado gráficos o visualizaciones que representan el historial de consumo eléctrico de manera fácil de entender.

Las visualizaciones son claras y proporcionan información relevante sobre el consumo eléctrico a lo largo del tiempo.


Se han realizado pruebas para garantizar que la función de historial de consumo eléctrico se integra correctamente en la aplicación.

**Comment by todotirreno** [comment]
Duplicado
