### ISSUE TITLE
#TK Desde Soporte no se puede navegar a otras pestañas

### ISSUE THREAD

**Issue by todotirreno** [Dev-Full-Solutions/AnalizArApp#132]
Vuelve siempre a Contacto

**Comment by danielpozzo** [comment]
Bug solucionado. Cambié el menú inferior (íconos) por el botón VOLVER que redirige al usuario a la activity Contacto por si desea realizar alguna otra acción en ella.

**Comment by todotirreno** [comment]
Solucionado. Cierro la incidencia.
