### ISSUE TITLE
#TK Completar retrospectiva del sprint 2

### ISSUE THREAD

**Issue by todotirreno** [Dev-Full-Solutions/AnalizArApp#133]
Enlace a la retrospectiva [acá](https://ideaboardz.com/for/Retrospective%20Sprint%202/5085168)

- [x] @todotirreno 
- [x] @danielpozzo 
- [x] @DiegolPl 
- [ ] @ChristMorales 
- [ ] @KaterinnePeralta 
- [x] @anibal-morales 
- [ ] @NoeCoast 
- [x] @LauraRodriguez22 
- [ ] @NoeVelaz

**Comment by danielpozzo** [comment]
Completé mi participación en la Retrospective del Sprint2.

**Comment by anibal-morales** [comment]
Retrospectiva completada

**Comment by LauraRodriguez22** [comment]
Restrospectiva del sprint 2 Completada.

**Comment by danielpozzo** [comment]
Requerimiento cerrado.
