### ISSUE TITLE
#US14 Como usuario quiero administrar mis alertas para poder configurarlas cuando lo desee.

### ISSUE THREAD

**Issue by danielpozzo** [Dev-Full-Solutions/AnalizArApp#15]

**Comment by danielpozzo** [comment]
Actualización de historias de usuario.

**Comment by danielpozzo** [comment]
@ChristMorales continuando con el desarrollo de la funcionalidad de la activity que realizaste en el sprint anterior, habría que cargar las tareas necesarias para abordar su realización.

**Comment by todotirreno** [comment]
Duplicado
