### ISSUE TITLE
#US02 Como usuario quiero un sistema de validación simple para tener un inicio de sesión seguro.

### ISSUE THREAD

**Issue by DiegolPl** [Dev-Full-Solutions/AnalizArApp#2]
La aplicación debe tener un sistema que tenga algún tipo de validación para evitar que mi cuenta sea utilizada por alguien ajeno a la misma. Para ello se implementará un sistema de autenticación mediante Firebase.

Tareas #US02

- [x] Crear cuenta en Firebase
- [x] Crear una aplicación en Firebase
- [x] Implementar Firebase en nuestro proyecto
- [x] Verificar que usuario y contraseña sean válidos 
- [x] Hacer que nuestro botón de "Acceder" consulte si existe el usuario y contraseña
- [x] En caso de estar OK, redirigir a Home. Caso contrario, mensaje del error

**Comment by danielpozzo** [comment]
@DiegolPl en función de lo investigado a lo largo de esta primer semana sería importante detallar las tareas (#TKxx) necesarias para su desarrollo.
