### ISSUE TITLE
#US18 Como usuario registrado quiero ver la pantalla "Onboarding 2" para seguir conociendo las características de la app.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizArApp#20]
- [x] #TK01 Crear un diseño atractivo y coherente con la marca para la pantalla de "Onboarding 2".
- [x] #TK08 Diseñar y preparar la imagen, el título, el párrafo, el botón "Seguir", el botón "Atrás" y el botón "Saltar" de acuerdo con las especificaciones del manual de estilo de la marca.
- [x] #TK02 Crear la estructura de la pantalla.
- [x] #TK03 Agregar la imagen, el título, el párrafo, el botón "Seguir", el botón "Atrás" y el botón "Saltar" a la pantalla.
- [x] #TK04 Configurar la acción del botón "Seguir" para que lleve al usuario a la tercera parte del proceso de Onboarding.
- [x] #TK09 Configurar la acción del botón "Atrás" para que lleve al usuario a la primera parte del proceso de Onboarding.
- [x] #TK10 Configurar la acción del botón "Saltar" para que lleve al usuario a la pantalla del Login.
- [x] #TK05 Realizar pruebas para asegurarse de que la pantalla se ve y se comporta como se espera.
- [x] #TK06 Verificar que los botones "Seguir", "Atrás" y "Saltar" funcionen correctamente.
- [x] #TK07 Realizar una revisión de código con otros miembros del equipo para asegurarse de que la implementación cumpla con los estándares pretendidos.

**Comment by todotirreno** [comment]
Definición de terminado: activity funcional con navegación
