### ISSUE TITLE
#US19 Como usuario registrado quiero ver la pantalla "Onboarding 3" para informarme sobre la última parte de la presentación de la app.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizArApp#21]
- [x] #TK01 Crear un diseño atractivo y coherente con la marca para la pantalla de "Onboarding 3".
- [x] #TK08 Diseñar y preparar la imagen, el título, el párrafo, el botón "Seguir", el botón "Atrás" y el botón "Saltar" de acuerdo con las especificaciones del manual de estilo de la marca.
- [x] #TK02 Crear la estructura de la pantalla.
- [x] #TK03 Agregar la imagen, el título, el párrafo, el botón "Seguir" y el botón "Atrás" a la pantalla.
- [x] #TK04 Configurar la acción del botón "Seguir" para que lleve al usuario a la pantalla del Login.
- [x] #TK11 Configurar la acción del botón "Atrás" para que lleve al usuario a la segunda parte del proceso de Onboarding.
- [x] #TK05 Realizar pruebas para asegurarse de que la pantalla se ve y se comporta como se espera.
- [x] #TK06 Verificar que los botones "Seguir" y "Atrás" funcionen correctamente.
- [x] #TK07 Realizar una revisión de código con otros miembros del equipo para asegurarse de que la implementación cumpla con los estándares pretendidos.

**Comment by todotirreno** [comment]
Definición de terminado: activity 100% funcional y con navegabilidad
