### ISSUE TITLE
#US26 Como usuario registrado quiero ver la pantalla "Contacto" para lograr conectarme con el área de soporte.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizArApp#28]
- [x] #TK01 Crear un diseño limpio y atractivo para la pantalla de Contacto con textos, los botónes de Incio, Soporte y un enlace a la empresa de desarrollo web y de aplicaciones digitales, Dev Full Solutions. 
- [x] #TK02 Crear la estructura de la pantalla.
- [x] #TK03 Agregar los textos, los botones para volver al Incio, de contacto con Soporte (asistencia técnica sobre la app) y un enlace a la empresa de desarrollo web y de aplicaciones digitales, Dev Full Solutions.
- [x] #TK04 Configurar la navegabilidad del botón Inicio para que realice la acción requerida.
- [x] #TK05 Realizar pruebas para asegurarse de que la pantalla se vea correctamente en diferentes dispositivos.
- [x] #TK07 Realizar una revisión de código con otros miembros del equipo para asegurarse de que la implementación sea la adecuada.

**Comment by danielpozzo** [comment]
Activity de contacto finalizada y probada. Navegabilidad realizada. Las funcionalidades de ésta activity se abordarán en el Sprint 2 según los lineamientos de la cátedra.

**Comment by danielpozzo** [comment]
Issue cerrada.
