### ISSUE TITLE
#US05 Como usuario quiero poder gestionar mi perfil de usuario para tener actualizados mis datos personales.

### ISSUE THREAD

**Issue by ChristMorales** [Dev-Full-Solutions/AnalizArApp#3]

**Comment by danielpozzo** [comment]
@ChristMorales @DiegolPl hemos unificado las historias #US05 y #US06 en una sola porque están relacionadas en su funcionalidad.
Resta cargar las tareas necesarias para desarrollar su funcionalidad.

**Comment by NoeCoast** [comment]
El objetivo fue incorporado en la #23
