### ISSUE TITLE
#TK Crear el Diagrama de Clases.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizArApp#31]
- [x] #TK26 Identificar todas las clases relevantes del sistema.
- [x] #TK27 Para cada clase, identificar los atributos o propiedades que deseas asociar con esa clase.
- [x] #TK28 Definir los métodos o funciones que pueden ser realizados por objetos de cada clase. 
- [x] #TK29 Establecer las relaciones entre las clases.
- [x] #TK30 Especificar la multiplicidad.
- [x] #TK31 Dibujar el Diagrama de Clases.
- [x] #TK32 Compartir el diagrama de clases con otros miembros del equipo para obtener retroalimentación y validar el diseño.

**Comment by todotirreno** [comment]
Definición de terminado: diagrama en /documentación
