### ISSUE TITLE
#US03 Como usuario quiero un sistema de validación doble factor para un nivel de seguridad más optimizado.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizArApp#6]

**Comment by KaterinnePeralta** [comment]
Tareas #US03
Diseñar la interfaz de usuario para que los usuarios puedan configurar y utilizar la autenticación de doble factor.
Configura la generación de códigos de autenticación en la aplicación del usuario.
Crear una actividad solicitando el código de validación.
Crear una actividad que muestre que el código es correcto.

**Comment by danielpozzo** [comment]
Esta tarea apunta al producto deseado del proyecto. Como no tuvismos tiempo para abordar su desarrollo la cerramos, dejándola en carpeta para una versión posterior del producto.
