### ISSUE TITLE
#US04 Como usuario quiero un logout para que mis datos estén más protegidos.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizArApp#7]
- [x] Crear botón para cerrar sesión
- [x] Agregar función que cierre sesión en Firebase
- [x] Redirigir a la activity de Home

**Comment by KaterinnePeralta** [comment]
- [x] Tareas #US04 El menú debe tener un botón de cerrar sesión.
- [x] Redirigir a la actividad de login (Inicio de sesión).

**Comment by DiegolPl** [comment]
- [x] Crear botón para cerrar sesión
- [x] Agregar función que cierre sesión en Firebase
- [x] Redirigir a la activity de Home
