### ISSUE TITLE
#TK Optimizar formatos y estilos de diseño de las activities de la app para obtener un diseño accesible.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizArApp#85]
@danielpozzo  @NoeCoast @todotirreno @DiegolPl @ChristMorales @anibal-morales @KaterinnePeralta @NoeVelaz @LauraRodriguez22 

- [x] activity_alarmas_configuracion
- [x] activity_contacto
- [x] activity_login
- [x] activity_main
- [x] activity_mi_cuenta
- [x] activity_misalarmas1
- [x] activity_misconsumos
- [x] activity_olvidaste_contrasena
- [x] activity_onboarding1
- [x] activity_onboarding2
- [x] activity_onboarding3
- [x] activity_soporte
- [x] activity_video

**Comment by danielpozzo** [comment]
Asumo el desarrollo de esta tarea para cumplimentar los requisitos deseados.

**Comment by NoeCoast** [comment]
Tener en cuenta el enfoque de accesibilidad que se sumó al presente sprint. Revisar texto, botones, contraste de color, formulario, imágenes, alt en imágenes, etc.

El material de consulta se encuentra en el Drive general del grupo, en la daily 8, o bien, en el chat AnalizArApp.
Se sugiere, además, mantener comunicación al respecto con el equipo de testing.

**Comment by danielpozzo** [comment]
MVP de Consumos y Soporte finalizado y actualizado en la rama develop de GitHub para revisión.

**Comment by anibal-morales** [comment]
Mvp de Activity "Mi cuenta" finalizado y actualizado en la rama develop de GitHub para revisión.

**Comment by NoeCoast** [comment]
MVP de Main y Onboarding1 finalizado y actualizado en GitHub para su revisión.
