### ISSUE TITLE
#TK Adecuación del documento IEEE830, de acuerdo a las normas APA

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizArApp#93]

**Comment by NoeCoast** [comment]
Información a aplicar: https://normas-apa.org/etiqueta/normas-apa-2023/

**Comment by NoeCoast** [comment]
@LauraRodriguez22

**Comment by LauraRodriguez22** [comment]
- [x] Armar documento con propuestas de cambios para la adecuacion del docuemento IEEE830.
- [x] Aplicar las reglas de las normas APA al documento IEEE830.
