### ISSUE TITLE
#TK Crear demo final en video con participación de todo el equipo describiendo todas las funcionalidades para mostrar el producto terminado.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizArApp#95]
Todo el equipo debe participar de la producción y realización del video.
Por favor, ir autoasignándose la tarea.

- [x] @DiegolPl  
- [x] @todotirreno 
- [x] @ChristMorales  
- [x] @KaterinnePeralta  
- [x] @anibal-morales 
- [x] @NoeVelaz  
- [x] @danielpozzo 
- [x] @NoeCoast 
- [x] @LauraRodriguez22 

**NOTA:** 23 de octubre de 2023, asigno la tarea al resto de integrantes que aún no se autoasignaron en la misma.
**NOTA 2:** Tildar los checklist a medida que finalicen sus producciones individuales para compaginar el material y proceder a la entrega del requerimiento.

**Comment by danielpozzo** [comment]
Requerimiento completado.
