### ISSUE TITLE
#TK Exportar la aplicación en un archivo para poder probarlo y subirla a GitHub.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizArApp#96]

**Comment by todotirreno** [comment]
- [x] tag
- [x] Generar release
- [x] Exportar apk
- [x] Subir al repo
- [x] merge a main

Definición de terminado: apk en repo y en "releases", v0.1 en main

**Comment by todotirreno** [comment]
Para la descripción de la versión se me ocurrió escribir algo así:

-Autenticación con Firebase
-Visualización de consumos diarios, semanales y mensuales
-Colores en gráficos de acuerdo a umbrales de consumo
-Visualizar, crear, editar y eliminar alarmas de acuerdo al umbral de consumo deseado
-Demostraciones con imágenes y video
-Visualización y edición de información de la cuenta
-Soporte técnico y contacto con equipo de desarrollo
