### ISSUE TITLE
#US41 Como usuario quiero ver la funcionalidad completa de la activity "Login" para poder loguearme dentro de la aplicación.

### ISSUE THREAD

**Issue by danielpozzo** [Dev-Full-Solutions/AnalizArApp#99]
- [x] Implementar algún servicio de autenticación para validar el ingreso del usuario. 
- [x] Agregar los usuarios existentes en la aplicación web
- [x] Configurar dicho servicio

**Comment by DiegolPl** [comment]
Implementado Firebase
